# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(150, 310, 101, 31))
        self.save_button.setObjectName("save_button")
        self.status_frame = QtWidgets.QFrame(self.centralwidget)
        self.status_frame.setGeometry(QtCore.QRect(10, 200, 391, 80))
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        self.status_label = QtWidgets.QLabel(self.status_frame)
        self.status_label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.status_label.setObjectName("status_label")
        self.radio_student = QtWidgets.QRadioButton(self.status_frame)
        self.radio_student.setGeometry(QtCore.QRect(80, 30, 82, 17))
        self.radio_student.setObjectName("radio_student")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio_student)
        self.radio_staff = QtWidgets.QRadioButton(self.status_frame)
        self.radio_staff.setGeometry(QtCore.QRect(170, 30, 82, 17))
        self.radio_staff.setObjectName("radio_staff")
        self.buttonGroup.addButton(self.radio_staff)
        self.radio_both = QtWidgets.QRadioButton(self.status_frame)
        self.radio_both.setGeometry(QtCore.QRect(280, 30, 82, 17))
        self.radio_both.setObjectName("radio_both")
        self.buttonGroup.addButton(self.radio_both)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 391, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_frame = QtWidgets.QFrame(self.frame)
        self.name_frame.setGeometry(QtCore.QRect(0, 0, 391, 80))
        self.name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_frame.setObjectName("name_frame")
        self.name_input = QtWidgets.QLineEdit(self.name_frame)
        self.name_input.setGeometry(QtCore.QRect(80, 30, 281, 20))
        self.name_input.setObjectName("name_input")
        self.name_label = QtWidgets.QLabel(self.name_frame)
        self.name_label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.name_label.setObjectName("name_label")
        self.age_frame = QtWidgets.QFrame(self.centralwidget)
        self.age_frame.setGeometry(QtCore.QRect(10, 110, 391, 80))
        self.age_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.age_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.age_frame.setObjectName("age_frame")
        self.age_input = QtWidgets.QLineEdit(self.age_frame)
        self.age_input.setGeometry(QtCore.QRect(80, 30, 281, 20))
        self.age_input.setObjectName("age_input")
        self.age_label = QtWidgets.QLabel(self.age_frame)
        self.age_label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.age_label.setObjectName("age_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 406, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test 10"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.status_label.setText(_translate("MainWindow", "Status"))
        self.radio_student.setText(_translate("MainWindow", "Student"))
        self.radio_staff.setText(_translate("MainWindow", "Staff"))
        self.radio_both.setText(_translate("MainWindow", "Both"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.age_label.setText(_translate("MainWindow", "Age"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
